version: '3'

services:
  edgy:
    image: koalafy/edgy:edge
    depends_on:
      - 'redis'
      - 'minio'
    volumes:
      - ../certs:/app/certs
    ports:
      - 3000:3000
    environment:
      - REDIS_URI=redis:6379
      - EDGY_REGION=dev-1
      - S3_GATEWAY=minio

  minio:
    image: minio/minio
    volumes:
      - ~/Warehouse/minio:/data
      - ../certs:/certs
    ports:
      - 3001:9000
    command: server /data --certs-dir="/certs"
    healthcheck:
      test:
        ['CMD', 'curl', '-f', '-k', 'https://localhost:9000/minio/health/live']
      interval: 15s
      timeout: 20s
      retries: 3
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

  redis:
    image: redis:latest
    volumes:
      - ~/Warehouse/redis:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli', 'ping']
      interval: 15s
      timeout: 20s
      retries: 3
